project:
  type: book
  output-dir: _book

book:
  title: "Embedded AI: Principles, Algorithms, and Applications"
  reader-mode: true
  cover-image: cover.png
  favicon: cover.png
  page-footer:
    left: |
      Embedded AI written and edited by Vijay Janapa Reddi and Song Han.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  author: "Vijay Janapa Reddi (Harvard University) and Song Han (MIT)"
  date: "9/5/2023"
  chapters:
    - index.qmd
    - about.qmd
    - introduction.qmd
    - tinyml.qmd
    - primer.qmd
    - mlworkflow.qmd
    - datacollection.qmd
    - preprocessing.qmd
    - feature_engineering.qmd
    - training.qmd
    - optimizations.qmd
    - deployment.qmd
    - mlops.qmd
    - references.qmd
appendices:
    - tools.qmd
    - resources.qmd

bibliography: references.bib

format:
  html:
    theme: zephyr
  pdf:
    documentclass: scrreprt



